language: rust
rust:
- stable
sudo: false
env:
  global:
    - secure: ihKHXQ4GSufL+3tP3nRur5PHGrHuJZGPvW74auBGrFBGo490bazKLc2Ut9I4wKt+8qeZQJz8RCtOaq2rJGgEr+3xDzFFQKCk+InYsJHA5XhSr56iWOo2Big4kM+m0YGLizAyAYnUsaR5EIec75JnvKk9ayn5YRkjUBsWruZGwK3xcygO88Zcap+nJbLOqbEqxN9d7b2hKNR/SG0k+4+PkczmuRnZjAuP91hdodFlH6mU0ycuv6qmxZZ+C3Pqd/9NDSO+NcYlMq1p+f7HCdxfwSVmEeJh0/ks6Ho/YfkX0mq9QfCEH35ZGCZgocnzoWkkekmT3pdty1VY/m7rgW3v0IGLXMj1tXoP2F8+Kzh2GW+gEk/vP/RrGs+CJvIquR34l/v4ZFIjJV9l2qT7Oif4o7MyKaYbhQNjQb1H19k6W9h6MY9Uniiq8RPqBlo92SSP0vAmzutRNS5H+OJbti0aA1UZO4f6ViUrk/bRYwIASzWFub/M8oa1vYb4Vd6WhL3WJq3hv2T2X9cMg+tlBLaXOuydxgHTsLM0aAlkR1OBa2ZUn2VFyYrBDtu07Iy3KkU74Tuq9RLdRXRWOhwyriZAEo0abQpOFKqHxYNFoMoraUIK5RwUcVKg6zj5mmgqfiRs+KIjasdtu542fpfXzyyp8TVa/8OHxOHFxq2j3qH06SI=
