language: rust
rust:
- stable
sudo: false
env:
  global:
  - secure: JVnh/Wyggd59i0HKK8GCJ4iaJPYtVanqy0W87zCmEFtgqbYt92UQvioiaWAqAtQBbeHVE0/1uSSBNIvujCGxnky+ybmky378g1C1EGFkNS+AsKynJsbKl+mWkmSS59jitNo03lgtd466jWcxrwC10KcE1d7p7MBWPXXi3+CDBRKePDER2mMApDvaTiD+7aj5LGamNt98AapUbHTaDmmAjcMHCXAQEIlpg8kxRXNEA53zeagHpHed5hDRRIPrHOvIKATAmw7b4519AKqtqFUW8dtqzKGvA1yVnuxhGGfFYFZeOLsKzheXEWCI1c1EXwbC2P2RedfZ+GCM8RrY7AJ8Xu+fSQMCPYAqidqHKyKz8+mYnWC8Wfdzy7zyHPM3LEm689Uw5iKivBZgcFM5eIjwveaKMSozWzbv7vrMBTOLyNW2QNK/3iYYkL0WJEvD3xRuTBjYgT67Pyp+5gANoesRAbz1n665xkVTNg/UOTa5fn0IMSVS97h6Ew/mNBkqx94bKqRGBhcBp+GIn2DSi8vmkUWWE1E33K1+glDXHMpY4bUH4CGyk6C3/nsGltvOeMXTDog8sdB6D3x3U5rtHpyAcYbd0ZJiib5f0VVvkSgzTUQB2inqiPhS2e8GWYymCvISnmkS9YHFIc9U6dFQjaDNfW6vte+gFyBFOcSnZc14ZQ8=