[package]
name = "bitmex"
version = "0.1.0-alpha.1"
authors = ["Weiyüen Wu <doomsplayer@gmail.com>"]

[dependencies]
hyper = "0.12"
hyper-tls = "0.3"

url = "1"
futures = "0.1"
tokio = "0.1"

failure = "0.1"
log = "0.4"

serde = "1"
serde_json = "1"
serde_derive = "1"

chrono = { version = "0.4", features = ["serde"] }
derive_more = "0.11"

hex = "0.3"
ring = "0.13"

# maplit = "1"

[features]
dev = []

[dev-dependencies]
dotenv = "0.13"
env_logger = "0.5"